'use strict';

/**
 * E2E Integration Tests – Hybrid Mode (Real AI Core)
 *
 * Prerequisites:
 *   - CF session: CF_HOME=/path/to/project cf login ...
 *   - Deployed AI models in SAP AI Core: sap-rpt-1-large, claude-opus-4-6
 *   - Run with: CF_HOME=. npm run test:e2e
 *
 * These tests submit real claims and verify that the full AI pipeline
 * (Claude extraction + RPT-1 prediction + Claude evaluation) produces
 * non-stub, meaningful output.
 */

const cds = require('@sap/cds');
const srv = cds.test('.', '--profile', 'hybrid');
const { GET, POST } = srv;

// ─── Auth setup ───────────────────────────────────────────────────────────────
beforeAll(() => {
  srv.axios.defaults.auth = { username: 'alice', password: 'alice' };
});

// ─── Poll helper ─────────────────────────────────────────────────────────────
async function pollStatus(ID, targetStatus, timeoutMs = 30000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const { data } = await GET(`/service/ClaimService/Claims(${ID})`);
    if (data.status_code === targetStatus) return data;
    if (data.status_code === 'failed') {
      throw new Error(`Claim ${ID} failed: ${data.lastError}`);
    }
    await new Promise(r => setTimeout(r, 500));
  }
  const { data } = await GET(`/service/ClaimService/Claims(${ID})`);
  throw new Error(`Timeout: claim ${ID} stuck at '${data.status_code}', expected '${targetStatus}'`);
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('E2E: Real AI pipeline (hybrid mode)', () => {
  test('auto claim runs through full pipeline with real AI responses', async () => {
    const { data: intake } = await POST('/api/intake/submitClaim', {
      title: 'Rear-end collision at traffic light — E2E test',
      description: 'My vehicle was rear-ended at a red light on Main Street. Police report filed on scene. ' +
        'The other driver admitted fault. Workshop estimate for bumper and chassis repair is attached.',
      claimAmount: 4800,
      currency: 'USD',
      claimType: 'auto',
      externalRef: `E2E-AUTO-${Date.now()}`
    });

    expect(intake.status).toBe('structuring');
    expect(intake.ID).toBeTruthy();

    // Pipeline may take up to 30s with real AI calls
    const claim = await pollStatus(intake.ID, 'evaluated', 60000);
    expect(claim.status_code).toBe('evaluated');

    // Verify StructuredData was populated by real AI (not stub)
    const { data: sdResult } = await GET(
      `/service/ClaimService/StructuredData?$filter=claim_ID eq ${intake.ID}`
    );
    expect(sdResult.value.length).toBe(1);
    const sd = sdResult.value[0];
    expect(sd.claimType).toBeTruthy();
    expect(sd.incidentDate).toBeTruthy();
    // Real AI should embed a description in rawExtraction (not the stub fallback text)
    const raw = JSON.parse(sd.rawExtraction);
    expect(raw.description).not.toContain('Stub extraction');

    // Verify Prediction was generated
    const { data: predResult } = await GET(
      `/service/ClaimService/Predictions?$filter=claim_ID eq ${intake.ID}`
    );
    expect(predResult.value.length).toBe(1);
    const pred = predResult.value[0];
    expect(pred.fraudScore).toBeGreaterThanOrEqual(0);
    expect(pred.fraudScore).toBeLessThanOrEqual(1);

    // Verify Evaluation was generated by real AI (not stub)
    const { data: evalResult } = await GET(
      `/service/ClaimService/Evaluations?$filter=claim_ID eq ${intake.ID}`
    );
    expect(evalResult.value.length).toBe(1);
    const ev = evalResult.value[0];
    expect(['low', 'medium', 'high', 'critical']).toContain(ev.riskLevel);
    expect(ev.summary).toBeTruthy();
    expect(ev.summary).not.toContain('AI Core not configured');
    expect(ev.recommendation).toBeTruthy();
  }, 90000);

  test('high-value property claim triggers elevated fraud score', async () => {
    const { data: intake } = await POST('/api/intake/submitClaim', {
      title: 'Complete contents loss — house fire — E2E test',
      description: 'Fire broke out in the kitchen and spread to the living room. Complete loss of electronics, ' +
        'furniture and personal belongings. Fire brigade report available.',
      claimAmount: 85000,
      currency: 'USD',
      claimType: 'property',
      externalRef: `E2E-PROP-${Date.now()}`
    });

    const claim = await pollStatus(intake.ID, 'evaluated', 60000);
    expect(claim.status_code).toBe('evaluated');

    const { data: predResult } = await GET(
      `/service/ClaimService/Predictions?$filter=claim_ID eq ${intake.ID}`
    );
    const pred = predResult.value[0];
    // High amount (> 50000) should yield elevated fraud score
    expect(pred.fraudScore).toBeGreaterThan(0.5);

    const { data: evalResult } = await GET(
      `/service/ClaimService/Evaluations?$filter=claim_ID eq ${intake.ID}`
    );
    const ev = evalResult.value[0];
    // High score should result in high or critical risk
    expect(['high', 'critical']).toContain(ev.riskLevel);
  }, 90000);

  test('analyst can approve an evaluated claim', async () => {
    const { data: intake } = await POST('/api/intake/submitClaim', {
      title: 'Minor fender bender — approve E2E test',
      description: 'Low-speed parking lot collision. Cosmetic damage only. Both parties exchanged details.',
      claimAmount: 1200,
      currency: 'USD',
      claimType: 'auto',
      externalRef: `E2E-APPROVE-${Date.now()}`
    });

    await pollStatus(intake.ID, 'evaluated', 60000);

    const { data } = await POST('/service/ClaimService/Claims_approveClaim', {
      ID: intake.ID,
      notes: 'E2E verified — low risk, consistent documentation. Approved.'
    });

    expect(data.status_code).toBe('approved');
    expect(data.reviewNotes).toContain('E2E verified');
  }, 90000);

  test('analyst can flag a suspicious claim', async () => {
    const { data: intake } = await POST('/api/intake/submitClaim', {
      title: 'Suspicious water damage claim — flag E2E test',
      description: 'Water damage to entire apartment two days before end of lease. ' +
        'No plumber report. Third claim in 12 months.',
      claimAmount: 22000,
      currency: 'USD',
      claimType: 'property',
      externalRef: `E2E-FLAG-${Date.now()}`
    });

    await pollStatus(intake.ID, 'evaluated', 60000);

    const { data } = await POST('/service/ClaimService/Claims_flagClaim', {
      ID: intake.ID,
      reason: 'E2E verified — third claim in 12 months, no supporting documentation. Escalate for investigation.'
    });

    expect(data.status_code).toBe('flagged');
    expect(data.reviewNotes).toContain('E2E verified');
  }, 90000);
});
