namespace fraud;
using { cuid, managed, Currency, sap } from '@sap/cds/common';

// ─── Code Lists ───────────────────────────────────────────────────────────────

@cds.autoexpose
entity ClaimTypes : sap.common.CodeList {
  key code : String(20);
}

@cds.autoexpose
entity ClaimStatuses : sap.common.CodeList {
  key code : String(20);
  @title: 'Criticality'
  criticality : Integer;
}

// ─── Core Entities ────────────────────────────────────────────────────────────

entity Claims : cuid, managed {
  @title: '{i18n>RawText}'
  rawText        : LargeString;
  @title: 'Title'
  title          : String(255);
  @title: 'Description'
  description    : localized String(5000);
  @title: 'Claim Amount'
  claimAmount    : Decimal(15, 2);
  @title: 'Currency'
  currency       : Currency;
  @title: 'Claim Type'
  claimType      : Association to ClaimTypes;
  @title: 'Status'
  status         : Association to ClaimStatuses default 'new';
  @title: '{i18n>ExternalRef}'
  externalRef    : String(100);
  @title: '{i18n>ReviewNotes}'
  reviewNotes    : String(2000);
  @title: '{i18n>RejectionReason}'
  rejectionReason: LargeString;
  lastError      : LargeString;
  @title: '{i18n>ParentClaim}'
  parentClaim    : Association to Claims;

  // ─── Pipeline comparison summaries (denormalized for the List Report) ─────────
  // Populated by the pipeline from the matching tracks so the list can show an
  // at-a-glance proprietary-vs-custom / open-source comparison even though each
  // claim now has many predictions/evaluations.
  @title: '{i18n>FraudScoreProprietary}'
  fraudScoreProprietary : Decimal(5, 4);
  @title: '{i18n>FraudScoreCustom}'
  fraudScoreCustom      : Decimal(5, 4);
  @title: '{i18n>RiskLevelProprietary}'
  riskLevelProprietary  : String(20);
  @title: '{i18n>RiskLevelOpenSource}'
  riskLevelOpenSource   : String(20);
  // Optional ground-truth label, set only for labeled demo cases (Tathergang
  // dataset) so the UI/tests can show predicted-vs-actual per model.
  @title: '{i18n>ActualFraud}'
  actualFraud           : Boolean;

  attachments    : Composition of many Attachments     on attachments.claim    = $self;
  structuredData : Composition of one  StructuredData   on structuredData.claim = $self;
  predictions    : Composition of many Predictions      on predictions.claim    = $self;
  evaluations    : Composition of many Evaluations      on evaluations.claim    = $self;
  runConfig      : Composition of many ModelRunConfig    on runConfig.claim      = $self;
}

// Requested model runs persisted from submitClaim — the "run setting".
// One row per (stage, modelName). For stage = 'evaluate', `inputPredictModel`
// names the predict model whose result that evaluation consumes, which is what
// makes the proprietary / open-source tracks isolated.
entity ModelRunConfig : cuid {
  claim             : Association to Claims;

  @title: 'Stage'
  stage             : String(10);   // 'predict' | 'evaluate'

  @title: 'Track'
  track             : String(20);   // 'proprietary' | 'custom' | 'opensource'

  @title: 'Model Name'
  modelName         : String(50);

  @title: 'Input Prediction Model'
  inputPredictModel : String(50);   // evaluate rows only

  @title: 'Sequence'
  sequence          : Integer;
}

entity Attachments : cuid, managed {
  claim     : Association to Claims;

  @title: 'Filename'
  filename  : String(255) not null;

  @title: 'Media Type'
  mediaType : String(100) not null;

  @Core.MediaType               : mediaType
  @Core.ContentDisposition.Filename: filename
  content   : LargeBinary;
}

entity StructuredData : cuid, managed {
  claim                : Association to Claims;

  @title: 'Claim Type'
  claimType            : String(50);

  @title: 'Incident Date'
  incidentDate         : Date;

  @title: 'Claim Amount'
  claimAmount          : Decimal(15, 2);

  @title: 'Description'
  description          : LargeString;

  @title: 'Extraction Confidence'
  extractionConfidence : Decimal(3, 2);

  @title: 'Raw Extraction (JSON)'
  rawExtraction        : LargeString;

  // Token usage of the structure-agent LLM call (output-token counting).
  @title: 'Prompt Tokens'
  promptTokens         : Integer;
  @title: 'Completion Tokens'
  completionTokens     : Integer;
  @title: 'Total Tokens'
  totalTokens          : Integer;

  fields               : Composition of many StructuredDataFields on fields.structuredData = $self;
}

// Claim-type-specific extracted fields stored as key-value pairs.
// Keys match the column names of the fraud training data (camelCase),
// enabling direct mapping to RPT-1 feature columns.
entity StructuredDataFields : cuid {
  structuredData : Association to StructuredData;

  @title: 'Field Name'
  fieldName      : String(100) not null;

  @title: 'Field Value'
  fieldValue     : String(500);
}

// ─── Fraud Training Data (split from fraud_oracle.csv) ────────────────────────
// Generated by scripts/split-training-data.ts — do not edit manually.
// Each entity is claim-type-specific. The predict step picks the right entity
// via the TRAINING_ENTITY_BY_TYPE registry in on-predictFraud-logic.ts.
// To add a new claim type: create a parallel FraudXxxTrainingData entity and
// register its name in that map.
// Future: replace DB sampling with HANA vector similarity search.

entity FraudAutoTrainingData {
  key rowNum             : Integer;
  month                  : String(20);
  weekOfMonth            : Integer;
  dayOfWeek              : String(20);
  make                   : String(50);
  accidentArea           : String(20);
  dayOfWeekClaimed       : String(20);
  monthClaimed           : String(20);
  weekOfMonthClaimed     : Integer;
  sex                    : String(10);
  maritalStatus          : String(20);
  age                    : Integer;
  fault                  : String(30);
  policyType             : String(50);
  vehicleCategory        : String(20);
  vehiclePrice           : String(30);
  policyNumber           : Integer;
  repNumber              : Integer;
  deductible             : Integer;
  driverRating           : Integer;
  daysPolicyAccident     : String(30);
  daysPolicyClaim        : String(30);
  pastNumberOfClaims     : String(20);
  ageOfVehicle           : String(30);
  ageOfPolicyHolder      : String(30);
  policeReportFiled      : String(5);
  witnessPresent         : String(5);
  agentType              : String(20);
  numberOfSuppliments    : String(20);
  addressChangeClaim     : String(20);
  numberOfCars           : String(20);
  year                   : Integer;
  basePolicy             : String(30);
  fraud                  : String(5);   // 'yes' | 'no'
}

entity FraudAutoValidationData {
  key rowNum             : Integer;
  month                  : String(20);
  weekOfMonth            : Integer;
  dayOfWeek              : String(20);
  make                   : String(50);
  accidentArea           : String(20);
  dayOfWeekClaimed       : String(20);
  monthClaimed           : String(20);
  weekOfMonthClaimed     : Integer;
  sex                    : String(10);
  maritalStatus          : String(20);
  age                    : Integer;
  fault                  : String(30);
  policyType             : String(50);
  vehicleCategory        : String(20);
  vehiclePrice           : String(30);
  policyNumber           : Integer;
  repNumber              : Integer;
  deductible             : Integer;
  driverRating           : Integer;
  daysPolicyAccident     : String(30);
  daysPolicyClaim        : String(30);
  pastNumberOfClaims     : String(20);
  ageOfVehicle           : String(30);
  ageOfPolicyHolder      : String(30);
  policeReportFiled      : String(5);
  witnessPresent         : String(5);
  agentType              : String(20);
  numberOfSuppliments    : String(20);
  addressChangeClaim     : String(20);
  numberOfCars           : String(20);
  year                   : Integer;
  basePolicy             : String(30);
  fraud                  : String(5);
}

entity FraudAutoTestData {
  key rowNum             : Integer;
  month                  : String(20);
  weekOfMonth            : Integer;
  dayOfWeek              : String(20);
  make                   : String(50);
  accidentArea           : String(20);
  dayOfWeekClaimed       : String(20);
  monthClaimed           : String(20);
  weekOfMonthClaimed     : Integer;
  sex                    : String(10);
  maritalStatus          : String(20);
  age                    : Integer;
  fault                  : String(30);
  policyType             : String(50);
  vehicleCategory        : String(20);
  vehiclePrice           : String(30);
  policyNumber           : Integer;
  repNumber              : Integer;
  deductible             : Integer;
  driverRating           : Integer;
  daysPolicyAccident     : String(30);
  daysPolicyClaim        : String(30);
  pastNumberOfClaims     : String(20);
  ageOfVehicle           : String(30);
  ageOfPolicyHolder      : String(30);
  policeReportFiled      : String(5);
  witnessPresent         : String(5);
  agentType              : String(20);
  numberOfSuppliments    : String(20);
  addressChangeClaim     : String(20);
  numberOfCars           : String(20);
  year                   : Integer;
  basePolicy             : String(30);
  fraud                  : String(5);
}

entity Predictions : cuid, managed {
  claim               : Association to Claims;

  // ─── Model provenance (one row per predict model run) ─────────────────────────
  @title: 'Track'
  track               : String(20);   // 'proprietary' | 'custom'
  @title: 'Provider'
  provider            : String(30);   // 'sap-rpt' | 'custom-ml'
  @title: 'Model Name'
  modelName           : String(50);   // 'sap-rpt-1-large' | 'gbc' | 'rf' | ...

  @title: 'Fraud Score'
  fraudScore          : Decimal(5, 4);

  @title: 'Predicted Class'
  predictedClass      : String(5);    // 'yes' | 'no'

  @title: 'Model Version'
  modelVersion        : String(50);

  @title: 'Status'
  status              : String(20);   // 'success' | 'stub' | 'failed'

  @title: 'Latency (ms)'
  latencyMs           : Integer;

  @title: 'Prediction Timestamp'
  predictionTimestamp : DateTime;
}

entity Evaluations : cuid, managed {
  claim             : Association to Claims;

  // ─── Model provenance (one row per evaluate model run) ────────────────────────
  @title: 'Track'
  track             : String(20);   // inherited from the input prediction
  @title: 'Provider'
  provider          : String(30);   // 'anthropic' | 'aicore-byom' | ...
  @title: 'Model Name'
  modelName         : String(50);
  @title: 'Prompt Version'
  promptVersion     : String(20);   // minimal reproducibility
  // The single prediction this evaluation reasoned about (isolated tracks).
  basedOnPrediction : Association to Predictions;

  // ─── LLM-as-classifier output (comparable vs ground truth) ────────────────────
  @title: 'Fraud Probability'
  fraudProbability  : Decimal(5, 4);
  @title: 'Fraud Decision'
  fraudDecision     : Boolean;
  // Predicted-vs-actual flag vs the claim's optional ground-truth label, set by
  // the evaluate step: 3 = correct (green), 1 = wrong (red), 0 = no label.
  // Drives Criticality of fraudDecision in the comparison table.
  @title: 'Decision Criticality'
  decisionCriticality : Integer;

  @title: 'Summary'
  summary           : LargeString;

  @title: 'Risk Level'
  riskLevel         : String(20);   // low | medium | high | critical

  @title: 'Key Factors (JSON)'
  keyFactors        : LargeString;

  @title: 'Recommendation'
  recommendation    : LargeString;

  // ─── Token usage (output-token counting) ──────────────────────────────────────
  @title: 'Prompt Tokens'
  promptTokens      : Integer;
  @title: 'Completion Tokens'
  completionTokens  : Integer;
  @title: 'Total Tokens'
  totalTokens       : Integer;

  @title: 'Status'
  status            : String(20);   // 'success' | 'stub' | 'failed'
  @title: 'Latency (ms)'
  latencyMs         : Integer;
}
